// <auto-generated />
using Mango.Services.ProductAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mango.Services.ProductAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.3.23174.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mango.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageLocalPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "Appetizer",
                            Description = "Crispy golden pastry filled with a flavorful blend of spiced potatoes and peas, deep-fried to perfection.",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "Samosa",
                            Price = 15.0
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "Entree",
                            Description = "Tender paneer cubes marinated in aromatic spices and yogurt, grilled to perfection with a smoky finish.",
                            ImageUrl = "https://placehold.co/602x402",
                            Name = "Paneer Tikka",
                            Price = 13.99
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "Dessert",
                            Description = "Delicious oven-baked pie with a flaky crust and a rich, sweet fruit filling.",
                            ImageUrl = "https://placehold.co/601x401",
                            Name = "Sweet Pie",
                            Price = 10.99
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "Entree",
                            Description = "A flavorful blend of spiced mashed vegetables served with buttery toasted pav, topped with onions and lemon.",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Pav Bhaji",
                            Price = 15.0
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryName = "Entree",
                            Description = "Soft melt-in-mouth cottage cheese dumplings simmered in a rich, creamy tomato and cashew gravy.",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Malai Kofta",
                            Price = 17.989999999999998
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryName = "Appetizer",
                            Description = "A savory street-food mix of puffed rice, crispy sev, fresh vegetables, and tangy tamarind-mint chutneys.",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Bhel",
                            Price = 8.9900000000000002
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryName = "Appetizer",
                            Description = "Crisp hollow puris filled with potatoes, chickpeas, and refreshing tangy spiced mint-flavored water.",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Pani Puri",
                            Price = 9.9900000000000002
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryName = "Appetizer",
                            Description = "Crispy golden wrappers stuffed with seasoned shredded vegetables and noodles, served with sweet chili sauce.",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Spring Roll",
                            Price = 7.9900000000000002
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryName = "Dessert",
                            Description = "Delicate, spongy cottage cheese patties soaked in chilled, saffron and cardamom infused sweetened milk.",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Rasmalai",
                            Price = 6.9900000000000002
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryName = "Dessert",
                            Description = "Crispy, spiral deep-fried sweet pretzels soaked in fragrant saffron and cardamom sugar syrup.",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Jalebi",
                            Price = 8.9900000000000002
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryName = "Dessert",
                            Description = "Traditional slow-cooked carrot pudding (Gajar Ka Halwa) enriched with pure ghee, khoya, and roasted dry fruits.",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Carrot Love",
                            Price = 7.9900000000000002
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryName = "Dessert",
                            Description = "Refreshing tropical dessert made with ripe Alphonso mangoes, creamy custard, and crushed pistachios.",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Mango Paradise",
                            Price = 5.9900000000000002
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
